inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/**/*'

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Rails:
  Enabled: true

Style/Lambda:
  Enabled: false
